// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RevenuQuebec.Infrastructure;

#nullable disable

namespace RevenuQuebec.Infrastructure.Migrations
{
    [DbContext(typeof(RevenuQuebecContext))]
    partial class RevenuQuebecContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RevenuQuebec.Core.Entities.AutreRevenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeclarationId")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.ToTable("AutresRevenus");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Avis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdjustmentNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmountPayable")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeclarationId")
                        .HasColumnType("int");

                    b.Property<string>("Deductions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GenerationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NetTax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresAgentReview")
                        .HasColumnType("bit");

                    b.Property<string>("TaxableIncome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Avis");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Declaration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AvisId")
                        .HasColumnType("int");

                    b.Property<string>("Citoyennete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ConfirmationExactitude")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateSoumission")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstBrouillon")
                        .HasColumnType("bit");

                    b.Property<int>("Etat")
                        .HasColumnType("int");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvisId")
                        .IsUnique()
                        .HasFilter("[AvisId] IS NOT NULL");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Declarations");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Justificatif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeclarationId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.ToTable("Justificatifs");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.RevenuEmploi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeclarationId")
                        .HasColumnType("int");

                    b.Property<string>("Employeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.ToTable("RevenusEmploi");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DateConnexion")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateDeconnexion")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEvenement")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeclarationId")
                        .HasColumnType("int");

                    b.Property<int>("Etat")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeclarationId");

                    b.ToTable("Statuts");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.AutreRevenu", b =>
                {
                    b.HasOne("RevenuQuebec.Core.Entities.Declaration", "Declaration")
                        .WithMany("AutresRevenus")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Declaration", b =>
                {
                    b.HasOne("RevenuQuebec.Core.Entities.Avis", "Avis")
                        .WithOne("Declaration")
                        .HasForeignKey("RevenuQuebec.Core.Entities.Declaration", "AvisId");

                    b.HasOne("RevenuQuebec.Core.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Declarations")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avis");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Justificatif", b =>
                {
                    b.HasOne("RevenuQuebec.Core.Entities.Declaration", "Declaration")
                        .WithMany("Fichiers")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.RevenuEmploi", b =>
                {
                    b.HasOne("RevenuQuebec.Core.Entities.Declaration", "Declaration")
                        .WithMany("RevenusEmploi")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Session", b =>
                {
                    b.HasOne("RevenuQuebec.Core.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Sessions")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Status", b =>
                {
                    b.HasOne("RevenuQuebec.Core.Entities.Declaration", "Declaration")
                        .WithMany("HistoriqueStatuts")
                        .HasForeignKey("DeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Declaration");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Avis", b =>
                {
                    b.Navigation("Declaration")
                        .IsRequired();
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Declaration", b =>
                {
                    b.Navigation("AutresRevenus");

                    b.Navigation("Fichiers");

                    b.Navigation("HistoriqueStatuts");

                    b.Navigation("RevenusEmploi");
                });

            modelBuilder.Entity("RevenuQuebec.Core.Entities.Utilisateur", b =>
                {
                    b.Navigation("Declarations");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
